// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCudFCXWzfGOCUinmjfw6exy-lYkP-xbrY',
    appId: '1:812957228443:android:7200b06809ca1e00a0d53e',
    messagingSenderId: '812957228443',
    projectId: 'dogether-3fe02',
    storageBucket: 'dogether-3fe02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7dC2c_d8wGSHw2JHy__twARbyoQmWaCQ',
    appId: '1:812957228443:ios:1eee551b2f6643d5a0d53e',
    messagingSenderId: '812957228443',
    projectId: 'dogether-3fe02',
    storageBucket: 'dogether-3fe02.appspot.com',
    androidClientId: '812957228443-pmb915a4jrfq6r4rnq4m61n3k53c784a.apps.googleusercontent.com',
    iosClientId: '812957228443-iqs7gfiph7h6b84k77rh4ffnfu9dsr1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogether',
  );
}
